### PR TITLE
libcloud: comment the teuthology_path to enable teuthology_branch

### PR DESCRIPTION
**Pull request by kshtsk**

### CODE REVIEW

**Comment by toabctl** [comment]
Having a commit message that describes the **why** you want to do this would be very helpful for reviewers...

**Comment by kshtsk** [comment]
> Having a commit message that describes the **why** you want to do this would be very helpful for reviewers...

I thought the title is self-explanatory: the teuthology_branch option does not take effect if the teuthology_path is present in the config.

**Comment by smithfarm** [comment]
On a more general note. . . would it be appropriate to move this project from `SUSE` to `ceph` namespace?

**Comment by kshtsk** [comment]
> On a more general note. . . would it be appropriate to move this project from `SUSE` to `ceph` namespace?

not sure it worth to do, if we decide to port it and introduce as teuthology-deploy tool in ceph/teuthology

**Pull request merged**
